// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC64FfO3XmamEViI8p8fBAq6o6xqglXGuo',
    appId: '1:721582080212:web:8e47c7a0af3733a37dfb41',
    messagingSenderId: '721582080212',
    projectId: 'helpu-login',
    authDomain: 'helpu-login.firebaseapp.com',
    storageBucket: 'helpu-login.appspot.com',
    measurementId: 'G-55XN2GYQSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzVBQaM_CLgvd-99VrwwLoTS0UrjyMNKI',
    appId: '1:721582080212:android:10c924b5089463497dfb41',
    messagingSenderId: '721582080212',
    projectId: 'helpu-login',
    storageBucket: 'helpu-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtYaSnJuOFQE1RuocEy7BjYP6N407zM4w',
    appId: '1:721582080212:ios:d2b726dd2e857f4c7dfb41',
    messagingSenderId: '721582080212',
    projectId: 'helpu-login',
    storageBucket: 'helpu-login.appspot.com',
    iosClientId: '721582080212-md61q0tojc2jhrm40tfcrd46b8g3tau5.apps.googleusercontent.com',
    iosBundleId: 'com.helpu.helpu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtYaSnJuOFQE1RuocEy7BjYP6N407zM4w',
    appId: '1:721582080212:ios:d2b726dd2e857f4c7dfb41',
    messagingSenderId: '721582080212',
    projectId: 'helpu-login',
    storageBucket: 'helpu-login.appspot.com',
    iosClientId: '721582080212-md61q0tojc2jhrm40tfcrd46b8g3tau5.apps.googleusercontent.com',
    iosBundleId: 'com.helpu.helpu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC64FfO3XmamEViI8p8fBAq6o6xqglXGuo',
    appId: '1:721582080212:web:61cab8b1a37bfe337dfb41',
    messagingSenderId: '721582080212',
    projectId: 'helpu-login',
    authDomain: 'helpu-login.firebaseapp.com',
    storageBucket: 'helpu-login.appspot.com',
    measurementId: 'G-PWCRYENJWJ',
  );
}
